# Generated by Django 3.2.3 on 2024-06-20 12:18

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_follow_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Такая почта уже зарегистрирована'}, max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя состоит не только из букв.', regex='^[a-zA-Zа-яА-Я\\s]*$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='В фамилии встречаются не только буквы пробелы и тире.', regex='^[a-zA-Zа-яА-Я\\s\\-]*$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='Имя пользователя содержит недопустимые символы')], verbose_name='Логин'),
        ),
    ]
